[package]
name = "magellan"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
